CDC-11: adding ProductSeeder
OscarRuina/backend-shopping-cart pull request #9
Opened 2022-01-16 21:23 UTC by JoaquinAman

2022-01-17 18:25 UTC, OscarRuina requested changes

2022-01-17 18:25 UTC, OscarRuina commented on src/main/java/com/team98/shoppingcart/config/seeder/ProductsSeeder.java
> +public class ProductsSeeder implements CommandLineRunner {
Falta la anotacion @Component

2022-01-18 12:35 UTC, matiasutn2019 approved these changes

2022-01-18 15:21 UTC, OscarRuina approved these changes

2022-01-18 15:22 UTC, merged